
import type { Metadata } from 'next'
import Head from 'next/head'
import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create ext app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (

    <html lang="en">
      <body>
      {children}
      </body>
    </html>
  )
}
